name: HubPlugin
main: me.mike1665.Main.Main
version: 1.0
description: Test
author: mike1665
commands:
    caoff:
    gadgets:
    stats:
    givetokens:
    givecoins:
    addstaff:
    cosmenu:
    parkour:
    setparkour1:
    parkour1:
    mountmenu:
    cp1:
    g-reward:
    sheeplol:
    test:
    rank:
    test:
    delfriend:
    friend:
    setmountspawn:
    unlockmount:
    ammotest:
    gadmenu:
    giveammo: