name: HubPlugin
main: me.mike1665.Main.Main
version: 1.0
description: Test
author: mike1665
commands:
    caoff:
    gadgets:
    stats:
    givepixls:
    givecoins:
    addstaff:
    cosmenu:
    parkour:
    setparkour1:
    parkour1:
    mountmenu:
    cp1: